### ISSUE TITLE
"Chrome-Only CSS" ... not so

### ISSUE THREAD

**Issue by WebMechanic** [browserstrangeness/browserstrangeness.github.io#15]
I presume you're aware that several "Chrome-Only CSS" hacks also turn red in EdgeHTML and Firefox.
For EdgeHTML # 3, 4, 5, 10, 12, 17, 18, 19, 25, 26, 27, 31, 35, 36, 39, 48, 49, 52, 56
For recent Firefox # 10, 12, 19, 20, 21, 23, 25, 27, 31, 33, 35, 39, 42, 44, 46, 49, 52, 54, 56.

Numbers from adding this to the current live page:
```css
h2 {counter-reset:hakk}
.styled_block {counter-increment:hakk}
.styled_block::after {
  z-index:27;
  position:absolute;
  font-size:smaller;
  content:counter(hakk);
  margin-top:-1em;
  height:1em;
}
```
